### ISSUE TITLE
Add HTTPS (!)

### ISSUE THREAD

**Issue by cvan** [decentralized-identity/decentralized-identity.github.io#3]
http://identity.foundation should be https://identity.foundation

**Comment by cvan** [comment]
I'd recommend registering `identify.foundation` with [Cloudflare](https://cloudflare.com): point the nameservers to CloudFlare's, create two `CNAME` records in Cloudflare:

```
@       decentralized-identity.github.io
www.    decentralized-identity.github.io
```

You can follow [my guide here](https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b) if it helps.

**Comment by cvan** [comment]
@csuwildcat bump! IMO this is pretty important. let me know if you want a hand with this.

**Comment by csuwildcat** [comment]
Is this free, I would love to do this, given the HTTPS block that is happening

**Comment by csuwildcat** [comment]
Added, via Cloudflare
